### ISSUE TITLE
不会分包

### ISSUE THREAD

**Issue by alexliyu** [TangXiaoLv/Android-Easy-MultiDex#10]
已经按照教程的配置了,
编译的时候console输出
DexKnife Processing ...
DexKnife Config: -just activity com.ctv.ui.splash.splashactivity
DexKnife Config: -keep com.ctv.sdk.**
DexKnife Config: -split **.**
DexKnife Config: -donot-use-suggest
DexKnife-From MergedJar: /home/alex/AndroidStudioProjects/ctv/app/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar
:app:genMainDexList

DexKnife: From Merged Jar: /home/alex/AndroidStudioProjects/ctv/app/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar

DexKnife Finished: 17ms

为毛还是只有一个dex, 8.3mb....

**Comment by TangXiaoLv** [comment]
@alexliyu 把你的分包配置发上来看看，检查下`multiDexEnabled true` 设置没

**Comment by TangXiaoLv** [comment]
@alexliyu #-donot-use-suggest 这句注释掉使用建议配置，，把#号加上

**Comment by alexliyu** [comment]
multiDexEnabled true
已經打開
#为注释符

#-----------主Dex中必要依赖的脚本配置-----------
#默认保留四大组件中其他三大组件(并计算其依赖树)，Activity组件选择性保留(使用-just activity 选项),若为空不保留任何Activity
-just activity com.ctv.ui.splash.SplashActivity

#-----------附加类-----------

# 如果你想要某个包路径在maindex中，则使用 -keep 选项，即使他已经在分包的路径中.若为空，不保留任意类

-keep com.ctv.sdk.**

# 保留单个类.

#-keep android.support.v7.app.AppCompatDialogFragment.class

# 这条配置可以指定这个包下类在第二及其他dex中.

#-split android.support.v?.**
#将全部类移出主Dex
-split **.**

# 不包含Android gradle 插件自动生成的miandex列表.(不使用建议的依赖树，注释掉表示使用,否则-just activity无效)

#-donot-use-suggest

# 不进行dex分包， 直到 dex 的id数量超过 65536.(设置自动执行分包策略)

#-auto-maindex

# 显示miandex的日志.

#-log-mainlist

**Comment by alexliyu** [comment]
折騰了好久, 發現如果是設置了
org.gradle.jvmargs=-Xmx2048M
則就不會自動分包.

**Comment by TangXiaoLv** [comment]
@alexliyu ![1](https://cloud.githubusercontent.com/assets/9014651/18415056/fa04d5dc-7816-11e6-8877-2aef4d146b2a.PNG)

我测试的是好的，调整虚拟机大小应该不会影响编译。你的是什么操作系统，gralde版本及插件版本，studio 版本都告知下。

**Comment by alexliyu** [comment]
這個應該是gralde自身的bug, 當設置org.gradle.jvmargs=-Xmx2048M後, 就算不用你的插件, 本身android studio也不會分包, 只有取消掉這個設置,纔會分包
android studio 2.1.3
gralde 2.14.1

**Comment by TangXiaoLv** [comment]
@alexliyu 你把instant run关掉试试，2.0以上如果打开增量编译，会导致debug包分包失效，原因是使用了instant run的拆包机制，如果打Release包应该没问题
