### ISSUE TITLE
Could not find com.ceabie.dextools:gradle-dexknife-plugin:2.0.1.

### ISSUE THREAD

**Issue by AllenCoder** [TangXiaoLv/Android-Easy-MultiDex#12]
`Error:Could not find com.ceabie.dextools:gradle-dexknife-plugin:2.0.1.
Searched in the following locations:
    file:/Applications/Android Studio2.2.app/Contents/gradle/m2repository/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.pom
    file:/Applications/Android Studio2.2.app/Contents/gradle/m2repository/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.jar
    https://jcenter.bintray.com/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.pom
    https://jcenter.bintray.com/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.jar
    file:/Users/allen/AndroidStudioProjects/juyoulicai_android_app/repo/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.pom
    file:/Users/allen/AndroidStudioProjects/juyoulicai_android_app/repo/com/ceabie/dextools/gradle-dexknife-plugin/2.0.1/gradle-dexknife-plugin-2.0.1.jar
Required by:
    :juyoulicai_android_app:unspecified`

**Comment by TangXiaoLv** [comment]
@AllenCoder 看下这个配置没

```
buildscript {
    repositories {
            maven { 
                url uri('repo')
        }
    }

    dependencies {
        ...
    }
}
```

**Comment by AllenCoder** [comment]
url uri('repo') 这个库你是本地编译发布的吧？

**Comment by TangXiaoLv** [comment]
@AllenCoder 嗯，本地库

**Comment by AllenCoder** [comment]
你的本地库，肯定不支持我们 gradle 拉取了，想个办法传到 jcenter 就好了

**Comment by TangXiaoLv** [comment]
@AllenCoder gradle拉取先检查本地库，再检查网络，并不冲突，你只要设置本地库目录，把相应的库文件放进取就能拉取

**Comment by TangXiaoLv** [comment]
@AllenCoder 已添加进jcenter
