### ISSUE TITLE
build 成功运行报ClassNotFoundException：Didn't find class

### ISSUE THREAD

**Issue by Heart2009** [TangXiaoLv/Android-Easy-MultiDex#19]
DexKnife Processing ...
DexKnife Adt Main: null
DexKnife Config: -dex-param --set-max-idx-number=4000
DexKnife Config: -auto-maindex
DexKnife Config: -log-mainlist

DexKnife Warning: NO SET split Or keep path, it will use Suggest!

DexKnife-From MergedJar: null
DexKnife Error: jarMerging is Null! Skip DexKnife. Please report All Gradle Log.
DexKnife Finished: 7ms

**Comment by TangXiaoLv** [comment]
@Heart2009 配置文件看下

**Comment by Heart2009** [comment]
配置文件没改，原样copy过去的

**Comment by TangXiaoLv** [comment]
注释-auto-maindex

**Comment by Heart2009** [comment]
试了下还是不行，请问这个最高支持的gradle版本和android plugin版本是多少 ？

**Comment by TangXiaoLv** [comment]
@Heart2009 本地测试gradle 2.2.2 version 2.14.1 OK

**Comment by Heart2009** [comment]
哦哦，难道跟工程有关，跟使用的其他插件有冲突？

**Comment by Heart2009** [comment]
可以加个联系方式吗？

**Comment by TangXiaoLv** [comment]
@Heart2009 给你发邮件了
