### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by aresa7796** [TangXiaoLv/Android-Easy-MultiDex#2]
配置后报错

`DexKnife Processing ...
DexKnife Config: -keep com.efangtec.efang.**
DexKnife Config: -donot-use-suggest
DexKnife Config: -auto-maindex
:app:genMainDexList
DexKnife: From Merged Jar: null
DexKnife: The Merged Jar is not exist! Can't be processed!
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> DexKnife Warnning: Main dex is EMPTY ! Check your config and project!`

**Comment by TangXiaoLv** [comment]
@切换到gradle 1.5.0

**Comment by TangXiaoLv** [comment]
@aresa7796 gradle 切换到 1.5.0
