### ISSUE TITLE
好像不能把一个class(比如MainActivity)的所有需要的依赖放入主dex

### ISSUE THREAD

**Issue by HCLXIDIAN** [TangXiaoLv/Android-Easy-MultiDex#21]
我的点击图标后的界面是一个登录界面,发现无数bug，就是说方法未找到,次级依赖(2,3,4级依赖)都没有放入主dex

**Comment by HCLXIDIAN** [comment]
#-----------主Dex中必要依赖的脚本配置-----------
#默认保留四大组件中其他三大组件(并计算其依赖树)，Activity组件选择性保留(使用-just activity 选项),若为空不保留任何Activity
-just activity com.tencent.broker.wxapi.WXEntryActivity
-just activity com.tencent.broker.ui.activity.SplashActivity
-just activity com.tencent.broker.ui.activity.WebBrowseActvity

#-----------附加类-----------
# 如果你想要某个包路径在maindex中，则使用 -keep 选项，即使他已经在分包的路径中.若为空，不保留任意类
-keep com.tencent.open.**
-keep com.tencent.broker.db.**
-keep com.tencent.beacon.**
-keep com.tencent.broker.logic.**
-keep com.tencent.mm.sdk.**
-keep com.tencent.mm.algorithm.**
-keep com.tencent.connect.**
-keep com.tencent.fit.ui.**
-keep com.tencent.fit.util.**



# 保留单个类.
-keep com.tencent.broker.db.DbCache.class
-keep com.tencent.broker.db.DbCache$DbData.class
-keep com.tencent.broker.db.DbCache$CacheData.class
-keep com.tencent.fit.ui.LayoutHeader$*.class
-keep com.tencent.fit.ui.LayoutHeader.class
-keep com.tencent.broker.ui.view.BaseView$*.class
-keep com.tencent.broker.ui.view.LoginView$*.class
-keep com.tencent.mm.sdk.openapi.SendAuth$*.class
-keep com.tencent.broker.common.Util$*.class
-keep com.tencent.connect.common.BaseApi$*.class
-keep tencent.com.cftutils.PassWdEncUtil.class
-keep com.tencent.fit.loglib.BuildConfig.class
-keep com.tencent.fit.tool.FitAsynTask.class
-keep com.tencent.broker.services.tasks.PusherTask.class
-keep com.tencent.broker.services.ICallback$Stub$Proxy.class
-keep com.tencent.broker.logic.LocalInfo$*.class




# 这条配置可以指定这个包下类在第二及其他dex中.
#-split android.support.v?.**
#将全部类移出主Dex
-split **.**

# 不包含Android gradle 插件自动生成的miandex列表.(不使用建议的依赖树，注释掉表示使用,否则-just activity无效)
#-donot-use-suggest

# (分割每个dex的方法数上限) 扩展参数:例如 --set-max-idx-number=50000
# 如果出现 DexException: Too many classes in --main-dex-list, main dex capacity exceeded：
# 表明限制的方法数小于main dex的必要方法数，调大到合适数值即可
#-dex-param --set-max-idx-number=65000

# 不进行dex分包， 直到 dex 的id数量超过 65536.(设置自动执行分包策略)
-auto-maindex

# 显示miandex的日志.
-log-mainlist

**Comment by TangXiaoLv** [comment]
@HCLXIDIAN -auto-maindex注释掉#-auto-maindex 打开表示禁用自定义分包策略

**Comment by HCLXIDIAN** [comment]
BrokerApplication里面用了CacheHelper,CacheHelper里面用了DbCache,然后就报错
dalvikvm: Could not find class 'com.tencent.broker.db.DbCache', referenced from method com.tencent.broker.logic.CacheHelper.<init>     想问下确定能把所以依赖的class放入主dex吗

**Comment by HCLXIDIAN** [comment]
忘了说了  我没有 使用  MultiDex.install(this);,因为我想异步加载分dex

**Comment by HCLXIDIAN** [comment]
我想把登录界面所有使用到的class都放入主dex

**Comment by TangXiaoLv** [comment]
@HCLXIDIAN 理论上加入了，你检查下mian dex

**Comment by TangXiaoLv** [comment]
@HCLXIDIAN 发面没计算进去的依赖可以手动指定keep

**Comment by TangXiaoLv** [comment]
@HCLXIDIAN 同一个包7.0好用4.4不好用？有检查过main dex么？
