### ISSUE TITLE
请问目前支持gradle的哪个版本？？？

### ISSUE THREAD

**Issue by johnx4** [TangXiaoLv/Android-Easy-MultiDex#23]

**Comment by TangXiaoLv** [comment]
gradle version 2.14.1
Android plugin version 2.2.3

**Comment by johnx4** [comment]
有个问题 使用了该插件后 原来maindexlist只有几千个类 现在发现变为接近两万个类

**Comment by TangXiaoLv** [comment]
主要看方法

**Comment by johnx4** [comment]
原来为什么这么少，加上这个插件后剧增？？？用的是这个命令 -filter-suggest

**Comment by johnx4** [comment]
而且-dex-param --set-max-idx-number= 这个命令明显无效

**Comment by TangXiaoLv** [comment]
@johnx4 不建议用-filter-suggest，尽量使用提供的配置

**Comment by johnx4** [comment]
怎样配置才能在自动生成的maindexlist基础上清除掉一些类，再有-dex-param --set-max-idx-number=这个命令用了还是会超出上限

**Comment by TangXiaoLv** [comment]
@johnx4 没有选项，但可以这么做，默认mian dex不包含任何方法 split ```**.**``` ,然后只-just activity和-keep需要的类即可，main dex会自动生成，不建议使用-dex-param --set-max-idx-number 对其他包分包，默认即可，除非你适配到4.0以下

**Comment by johnx4** [comment]
这样做的话等于是手动配置了吧，我现在就是这样做，要自己计算依赖，超麻烦

**Comment by TangXiaoLv** [comment]
@johnx4 -just activity自动计算依赖

**Comment by johnx4** [comment]
除了activity 其他的类无法自动计算

**Comment by ceabie** [comment]
1.5.8已兼容到 gradle 3.2，修复只使用-suggest-xx导致的额外增多类，可以只使用-suggest-xx对推荐的类列表过滤
