### ISSUE TITLE
Android 6.0 HTC M8w 编译之后无法安装

### ISSUE THREAD

**Issue by sumaro** [TangXiaoLv/Android-Easy-MultiDex#24]
![dex](https://cloud.githubusercontent.com/assets/8817011/23840253/bcb9ffce-07de-11e7-9413-dfe1cb8b6fea.png)
除了这一台6.0的测试机，其他低于6.0的设备都能正常安装，求助

**Comment by sumaro** [comment]
在 Appliction 中报错 ，我继承的是MultiDexApplication

**Comment by TangXiaoLv** [comment]
@sumaro 检查下依赖compile 'com.android.support:multidex:1.0.1' 加了没

**Comment by TangXiaoLv** [comment]
@sumaro gradl版本和插件是什么版本？

**Comment by sumaro** [comment]
我的gradle版本是gradle-3.3-all.zip，加上依赖compile 'com.android.support:multidex:1.0.1' 就可以了 ,
@TangXiaoLv 你的配置说明好像没有要添加这个依赖，谢谢啦
