### ISSUE TITLE
multiDexKeepFile疑问

### ISSUE THREAD

**Issue by coolegos** [TangXiaoLv/Android-Easy-MultiDex#25]
gradle插件1.5.0以后写起来比较的麻烦。所以想着直接使用`multiDexKeepFile`，但是`multiDexKeepFile`不会导致分dex，是哪里有问题吗？ 使用DexKnifePlugin是OK的。

```
multiDexEnabled true
multiDexKeepFile file('maindexlist.txt')
```

**Comment by ceabie** [comment]
multiDexKeepFile 只有keep 到maindex，而没有分出去的功能。DexKnifePlugin 的-suggest-keep 与之功能类似。分包要加 --minimal-main-dex选项，multiDexKeepFile 没有指定。

**Comment by coolegos** [comment]
谢了
