### ISSUE TITLE
just activity 不支持gradle 2.2.3?

### ISSUE THREAD

**Issue by weiyuant** [TangXiaoLv/Android-Easy-MultiDex#26]
`private static void filterActivity(Project project) {
        File file = project.file(DexSplitTools.DEX_KNIFE_CFG_TXT)
        if (file != null) {
            def justActivitys = [];
            file.eachLine { line ->
                //printf "read line ${line}\n";
                if (line.startsWith('-just activity')) {
                    line = line.replaceAll('-just activity', '').trim();
                    justActivitys.add(line)
                }
            }
            printf "-just activity size = ${justActivitys.size()}\n";
            if (justActivitys.size() != 0) {
                project.tasks.each { task ->
                    if (task.name.startsWith('collect') && task.name.endsWith('MultiDexComponents')) {
                        println "main-dex-filter: found task $task.name"
                        task.filter { name, attrs ->
                            String componentName = attrs.get('android:name')
                            if ('activity'.equals(name)) {
                                def result = justActivitys.find {
                                    componentName.endsWith("${it}")
                                }
                                def bool = result != null;
                                if (bool) {
                                    printf "main-dex-filter: keep ${componentName}\n"
                                }
                                return bool
                            }
                            return true
                        }
                    }
                }
            }
        }
    }`
在gradle2.2.3中没有collectReleaseMultiDexComponents

**Comment by TangXiaoLv** [comment]
@weiyuant 支持啊，我们用的就是2.2.3

**Comment by weiyuant** [comment]
1.5+采用的transfom 没看到兼容代码啊  我使用gradle2.2.3 配置just activity 无效啊 并不会合成到主dex文件中

**Comment by TangXiaoLv** [comment]
@weiyuant 看下你的配置文件

**Comment by weiyuant** [comment]
#为注释符

#-----------主Dex中必要依赖的脚本配置-----------(支持依赖检测)
#默认保留四大组件中Service,ContentProvider,BroadcastReceiver三大组件,Activity组件选择性保留,若为空不保留任何Activity
-just activity com.elc.app.activity.WelcomeActivity
-just activity com.elc.app.activity.MainActivity
-just activity com.elc.app.activity.SplashActivity
-just activity com.elc.app.activity.ShareTransferActivity
-just activity cn.jpush.android.ui.PushActivity


#-----------附加类-----------(不支持依赖检测)
# 如果你想要某个包路径在maindex中，则使用 -keep 选项，即使他已经在分包的路径中.若为空，不保留任意类
#-keep com.elc.app.**

# 保留单个类.
#-keep android.support.v7.app.AppCompatDialogFragment.class
#-keep com.elc.app.activity.WelcomeActivity.class

# 这条配置可以指定这个包下类在第二及其他dex中.
#-split android.support.v?.**
#将全部类移出主Dex
-split **.**

# 不包含Android gradle 插件自动生成的miandex列表.(不使用建议的依赖树，注释掉表示使用,否则-just activity无效)
#-donot-use-suggest

# (分割每个dex的方法数上限) 扩展参数:例如 --set-max-idx-number=50000
# 如果出现 DexException: Too many classes in --main-dex-list, main dex capacity exceeded：
# 表明限制的方法数小于main dex的必要方法数，调大到合适数值即可
-dex-param --set-max-idx-number=20000

# 注释掉将执行自定义dex分包，否则执行默认分包.
#-auto-maindex

# 显示miandex的日志.
-log-mainlist

**Comment by TangXiaoLv** [comment]
@weiyuant 关闭instant run试试

**Comment by weiyuant** [comment]
没开启Instant Run

**Comment by weiyuant** [comment]
有联系方式吗？加下QQ 微信

**Comment by TangXiaoLv** [comment]
@weiyuant QQ发你邮件了

**Comment by weiyuant** [comment]
weiyuant@163.com  刚才没收到

**Comment by TangXiaoLv** [comment]
添加官方默认分包
```
android{
	defaultConfig {
		multiDexEnabled true
	}
}

dependencies { 
    compile 'com.android.support:MultiDex:1.0.1'
}
```
