### ISSUE TITLE
dexknife.txt相关问题

### ISSUE THREAD

**Issue by woitaylor** [TangXiaoLv/Android-Easy-MultiDex#5]
# 为注释符
# -----------主Dex中必要依赖的脚本配置-----------
# 默认保留四大组件中其他三大组件，Activity组件选择性保留(使用-just activity 选项),若为空默认保留所有Activity

-just activity com.ceabie.demo.MainActivity

这个是指
# -just activity com.ceabie.demo.MainActivity（注释掉或者不写）

还是-just activity（选项不写）？用来保留所有的Activity？
# 将全部类移出主Dex

-split **.**
上面这个选项是不是不包括四大组件？它跟下面一条有冲突吗？
# 这条配置可以指定这个包下类在第二及其他dex中.
# android.support.v?.**
# 显示miandex的日志.
# -log-mainlist

这个日志是在哪里显示？

如果是有多个依赖module是不是在主app中使用？
谢谢！

**Comment by TangXiaoLv** [comment]
@woitaylor 谢提醒，更新了下分包注释。在这里重新说明下。
1：被#注释掉的行不会参与到插件分包计算，仅仅是普通的注释。 
2：-just activity 是关键字，后面跟需要保留到main dex 中的Activity包全路径，指定后插件会自动算出其依赖类。#-just activity com.ceabie.demo.MainActivity注释掉或不写将不会保留任何Activity
3:-split 关键字表示需要移出main dex的包路径，比如我先-keep a.b.c.**(包路径)，但是里面又有些是不需要放入main dex，我就可以用-split a.b.c.d.** 从中把不需要的包移出，而-split **.** 就表示将所有的类都移出main dex，当-keep 和-split 同时对同一个包路径使用，-keep 覆盖-split
4：-split 关键字可选，直接写上包路径是一样的效果，加上关键字为了容易区分，所以跟下面一条不冲突。
5：-log-mainlist 日志在build的时候会出现在Messages中，由于都是白色，不是很容易分辨。
6：多个依赖module的话只要在主app使用就可以，会自动计算出其他module中的依赖关系。
