### ISSUE TITLE
5.0以下手机运行后找不到MyApplication，5.0以上没有问题

### ISSUE THREAD

**Issue by tmac010sjh** [TangXiaoLv/Android-Easy-MultiDex#8]
classpath 'com.android.tools.build:gradle:2.1.3'
classpath 'com.ceabie.dextools:gradle-dexknife-plugin:2.0.1'
instant run关掉了

**Comment by TangXiaoLv** [comment]
@tmac010sjh gradle 换成1.5.0试试，或者把配置信息，和错误发来看下

**Comment by tmac010sjh** [comment]
@TangXiaoLv 抱歉，是我自己的问题。。。
